//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK_TBL()
        {
            this.ORDER_TBL = new HashSet<ORDER_TBL>();
        }
    
        public decimal BOOK_ID { get; set; }
        public Nullable<decimal> BOOK_CODE { get; set; }
        public string BOOK_NAME { get; set; }
        public Nullable<decimal> BOOK_PRICE { get; set; }
        public Nullable<bool> BOOK_STATE { get; set; }
        public string NOTES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_TBL> ORDER_TBL { get; set; }
    }
}
