//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHILD_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHILD_TBL()
        {
            this.CLASSES_TBL = new HashSet<CLASSES_TBL>();
            this.DUES_TBL = new HashSet<DUES_TBL>();
            this.EVALUATION_TBL = new HashSet<EVALUATION_TBL>();
            this.EVENT_SUBS_TBL = new HashSet<EVENT_SUBS_TBL>();
            this.EVENTS_TBL = new HashSet<EVENTS_TBL>();
            this.MONTHLY_SUBS_TBL = new HashSet<MONTHLY_SUBS_TBL>();
            this.ORDER_TBL = new HashSet<ORDER_TBL>();
            this.VISIT_TBL = new HashSet<VISIT_TBL>();
        }
    
        public decimal CLD_ID { get; set; }
        public Nullable<decimal> CLD_CODE { get; set; }
        public byte[] CLD_NAME { get; set; }
        public Nullable<System.DateTime> CLD_P_DATE { get; set; }
        public string CLD_GEN { get; set; }
        public string CLD_LVL { get; set; }
        public Nullable<decimal> PAR_ID { get; set; }
    
        public virtual PARENT_INFO_TBL PARENT_INFO_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLASSES_TBL> CLASSES_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUES_TBL> DUES_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVALUATION_TBL> EVALUATION_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENT_SUBS_TBL> EVENT_SUBS_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTS_TBL> EVENTS_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MONTHLY_SUBS_TBL> MONTHLY_SUBS_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_TBL> ORDER_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISIT_TBL> VISIT_TBL { get; set; }
    }
}
