//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASSES_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLASSES_TBL()
        {
            this.SUBJECT_PER_CLASS_TBL = new HashSet<SUBJECT_PER_CLASS_TBL>();
        }
    
        public decimal CLS_ID { get; set; }
        public Nullable<decimal> CLS_CODE { get; set; }
        public string CLS_NAME { get; set; }
        public string CLS_NANY { get; set; }
        public Nullable<decimal> SUBJ_ID { get; set; }
        public Nullable<decimal> CLD_ID { get; set; }
        public Nullable<bool> CLS_STATE { get; set; }
    
        public virtual CHILD_TBL CHILD_TBL { get; set; }
        public virtual SUBJECT_TBL SUBJECT_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBJECT_PER_CLASS_TBL> SUBJECT_PER_CLASS_TBL { get; set; }
    }
}
