//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUES_TBL
    {
        public decimal DUES_ID { get; set; }
        public Nullable<decimal> DUES_CODE { get; set; }
        public string DUES_NAME { get; set; }
        public Nullable<decimal> DUES_AMOUNT { get; set; }
        public Nullable<System.DateTime> DUES_PAY_DATE { get; set; }
        public Nullable<bool> DUES_STATE { get; set; }
        public Nullable<decimal> CLD_ID { get; set; }
    
        public virtual CHILD_TBL CHILD_TBL { get; set; }
    }
}
