//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_ACCOUNT_TBL
    {
        public decimal ACC_ID { get; set; }
        public Nullable<decimal> ACC_CODE { get; set; }
        public Nullable<System.DateTime> ACC_DATE { get; set; }
        public Nullable<System.TimeSpan> ACC_TIME { get; set; }
        public Nullable<decimal> ACC_PALANCE { get; set; }
        public Nullable<decimal> ACC_DISCOUNT { get; set; }
        public Nullable<decimal> ACC_OVER { get; set; }
        public Nullable<bool> ACC_STATE { get; set; }
        public string ACC_NOTE { get; set; }
        public decimal EMP_ID { get; set; }
    
        public virtual EMPLOYEE_TBL EMPLOYEE_TBL { get; set; }
    }
}
