//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE_TBL()
        {
            this.DRIVER_TBL = new HashSet<DRIVER_TBL>();
            this.EMP_ACCOUNT_TBL = new HashSet<EMP_ACCOUNT_TBL>();
            this.TEACHER_TBL = new HashSet<TEACHER_TBL>();
            this.USERS_TBL = new HashSet<USERS_TBL>();
        }
    
        public decimal EMP_ID { get; set; }
        public Nullable<decimal> EMP_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_N_NAME { get; set; }
        public string EMP_TYPE { get; set; }
        public Nullable<decimal> EMP_SAL { get; set; }
        public Nullable<decimal> EMP_WORK_HOUR { get; set; }
        public string EMP_JOB_SYS { get; set; }
        public Nullable<System.DateTime> EMP_EMPLOY_DATE { get; set; }
        public string EMP_ADD { get; set; }
        public string EMP_MOB { get; set; }
        public string EMP_SOCIAL_STATE { get; set; }
        public string EMP_DEPT { get; set; }
        public Nullable<bool> EMP_STATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRIVER_TBL> DRIVER_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_ACCOUNT_TBL> EMP_ACCOUNT_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_TBL> TEACHER_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERS_TBL> USERS_TBL { get; set; }
    }
}
