//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_SUBS_TBL
    {
        public decimal EVT_SUBS_ID { get; set; }
        public Nullable<decimal> EVT_SUBS_CODE { get; set; }
        public Nullable<decimal> EVT_SUBS_PRICE { get; set; }
        public Nullable<System.DateTime> EVT_SUBS_PAY_DATE { get; set; }
        public string EVT_SUBS_REQ { get; set; }
        public Nullable<decimal> EVT_ID { get; set; }
        public Nullable<decimal> CLD_ID { get; set; }
    
        public virtual CHILD_TBL CHILD_TBL { get; set; }
        public virtual EVENTS_TBL EVENTS_TBL { get; set; }
    }
}
