//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTS_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENTS_TBL()
        {
            this.EVENT_SUBS_TBL = new HashSet<EVENT_SUBS_TBL>();
        }
    
        public decimal EVT_ID { get; set; }
        public Nullable<decimal> EVT_CODE { get; set; }
        public string EVT_NAME { get; set; }
        public Nullable<System.DateTime> EVT_DATE { get; set; }
        public string EVT_CRAFT { get; set; }
        public Nullable<bool> EVT_PIC1 { get; set; }
        public Nullable<bool> EVT_PIC2 { get; set; }
        public Nullable<decimal> CLD_ID { get; set; }
    
        public virtual CHILD_TBL CHILD_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENT_SUBS_TBL> EVENT_SUBS_TBL { get; set; }
    }
}
