//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATHER_INFO_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FATHER_INFO_TBL()
        {
            this.PARENT_INFO_TBL = new HashSet<PARENT_INFO_TBL>();
        }
    
        public decimal FATHER_ID { get; set; }
        public Nullable<decimal> FATHER_CODE { get; set; }
        public string FATHER_NAME { get; set; }
        public string FATHER_SSID { get; set; }
        public string FATHER_MOB { get; set; }
        public string FATHER_JOB { get; set; }
        public string FATHER_EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARENT_INFO_TBL> PARENT_INFO_TBL { get; set; }
    }
}
