//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTHLY_SUBS_TBL
    {
        public decimal M_SUBS_ID { get; set; }
        public Nullable<decimal> M_SUBS_CODE { get; set; }
        public Nullable<decimal> M_SUBS_CONST_AMOUNT { get; set; }
        public Nullable<decimal> M_SUBS_TOTAL { get; set; }
        public Nullable<System.DateTime> M_SUBS_PAY_DATE { get; set; }
        public Nullable<bool> M_SUBS_STATE { get; set; }
        public Nullable<decimal> CLD_ID { get; set; }
        public Nullable<decimal> SUB_SUBS_ID { get; set; }
    
        public virtual CHILD_TBL CHILD_TBL { get; set; }
        public virtual SUB_SUBSCRIPTION_TBL SUB_SUBSCRIPTION_TBL { get; set; }
    }
}
