//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTHER_INFO_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOTHER_INFO_TBL()
        {
            this.PARENT_INFO_TBL = new HashSet<PARENT_INFO_TBL>();
        }
    
        public decimal MOTHER_ID { get; set; }
        public Nullable<decimal> MOTHER_CODE { get; set; }
        public string MOTHER_NAME { get; set; }
        public string MOTHER_SSID { get; set; }
        public string MOTHER_MOB { get; set; }
        public string MOTHER_JOB { get; set; }
        public string MOTHER_EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARENT_INFO_TBL> PARENT_INFO_TBL { get; set; }
    }
}
