//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMART_NURSERY_2024Entities : DbContext
    {
        public SMART_NURSERY_2024Entities()
            : base("name=SMART_NURSERY_2024Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOOK_TBL> BOOK_TBL { get; set; }
        public virtual DbSet<CHILD_TBL> CHILD_TBL { get; set; }
        public virtual DbSet<CLASSES_TBL> CLASSES_TBL { get; set; }
        public virtual DbSet<DEGREE_TBL> DEGREE_TBL { get; set; }
        public virtual DbSet<DRIVER_TBL> DRIVER_TBL { get; set; }
        public virtual DbSet<DUES_TBL> DUES_TBL { get; set; }
        public virtual DbSet<EMP_ACCOUNT_TBL> EMP_ACCOUNT_TBL { get; set; }
        public virtual DbSet<EMPLOYEE_TBL> EMPLOYEE_TBL { get; set; }
        public virtual DbSet<EVALUATION_TBL> EVALUATION_TBL { get; set; }
        public virtual DbSet<EVENT_SUBS_TBL> EVENT_SUBS_TBL { get; set; }
        public virtual DbSet<EVENTS_TBL> EVENTS_TBL { get; set; }
        public virtual DbSet<MONTHLY_SUBS_TBL> MONTHLY_SUBS_TBL { get; set; }
        public virtual DbSet<ORDER_TBL> ORDER_TBL { get; set; }
        public virtual DbSet<SUB_SUBSCRIPTION_TBL> SUB_SUBSCRIPTION_TBL { get; set; }
        public virtual DbSet<SUBJECT_PER_CLASS_TBL> SUBJECT_PER_CLASS_TBL { get; set; }
        public virtual DbSet<SUBJECT_TBL> SUBJECT_TBL { get; set; }
        public virtual DbSet<TEACHER_TBL> TEACHER_TBL { get; set; }
        public virtual DbSet<UNIFORM_TBL> UNIFORM_TBL { get; set; }
        public virtual DbSet<USERS_TBL> USERS_TBL { get; set; }
        public virtual DbSet<VEHICLE_TBL> VEHICLE_TBL { get; set; }
        public virtual DbSet<VISIT_TBL> VISIT_TBL { get; set; }
        public virtual DbSet<PARENT_INFO_TBL> PARENT_INFO_TBL { get; set; }
    }
}
