//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_TBL
    {
        public decimal ORDER_ID { get; set; }
        public Nullable<decimal> ORDER_CODE { get; set; }
        public string ORDER_TYPE { get; set; }
        public Nullable<decimal> ORDER_QTY { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<System.TimeSpan> ORDER_TIME { get; set; }
        public Nullable<decimal> ORDER_TOTAL_PRICE { get; set; }
        public Nullable<bool> IS_NEW_CLD { get; set; }
        public Nullable<bool> IS_MISSED { get; set; }
        public Nullable<decimal> CLD_ID { get; set; }
        public Nullable<decimal> BOOK_ID { get; set; }
        public Nullable<decimal> UNIFORM_ID { get; set; }
    
        public virtual BOOK_TBL BOOK_TBL { get; set; }
        public virtual CHILD_TBL CHILD_TBL { get; set; }
        public virtual UNIFORM_TBL UNIFORM_TBL { get; set; }
    }
}
