//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARENT_INFO_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARENT_INFO_TBL()
        {
            this.CHILD_TBL = new HashSet<CHILD_TBL>();
        }
    
        public decimal PAR_ID { get; set; }
        public Nullable<decimal> PAR_CODE { get; set; }
        public string PAR_NAME { get; set; }
        public Nullable<decimal> FATHER_ID { get; set; }
        public Nullable<decimal> MOTHER_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHILD_TBL> CHILD_TBL { get; set; }
        public virtual FATHER_INFO_TBL FATHER_INFO_TBL { get; set; }
        public virtual MOTHER_INFO_TBL MOTHER_INFO_TBL { get; set; }
    }
}
