//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_SUBSCRIPTION_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUB_SUBSCRIPTION_TBL()
        {
            this.MONTHLY_SUBS_TBL = new HashSet<MONTHLY_SUBS_TBL>();
        }
    
        public decimal SUB_SUBS_ID { get; set; }
        public Nullable<decimal> SUB_SUBS_CODE { get; set; }
        public string SUB_SUBS_NAME { get; set; }
        public Nullable<decimal> SUB_SUBS_AMOUNT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MONTHLY_SUBS_TBL> MONTHLY_SUBS_TBL { get; set; }
    }
}
