//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBJECT_PER_CLASS_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBJECT_PER_CLASS_TBL()
        {
            this.EVALUATION_TBL = new HashSet<EVALUATION_TBL>();
        }
    
        public decimal SUBJ_PER_CLS_ID { get; set; }
        public Nullable<decimal> SUBJ_PER_CLS_CODE { get; set; }
        public Nullable<System.DateTime> SUBJ_PER_CLS_DATE { get; set; }
        public Nullable<System.TimeSpan> SUBJ_PER_CLS_TIME { get; set; }
        public Nullable<decimal> CLS_ID { get; set; }
        public Nullable<decimal> SUBJ_ID { get; set; }
    
        public virtual CLASSES_TBL CLASSES_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVALUATION_TBL> EVALUATION_TBL { get; set; }
        public virtual SUBJECT_TBL SUBJECT_TBL { get; set; }
    }
}
