//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBJECT_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBJECT_TBL()
        {
            this.CLASSES_TBL = new HashSet<CLASSES_TBL>();
            this.SUBJECT_PER_CLASS_TBL = new HashSet<SUBJECT_PER_CLASS_TBL>();
        }
    
        public decimal SUBJ_ID { get; set; }
        public Nullable<decimal> SUBJ_CODE { get; set; }
        public string SUBJ_NAME { get; set; }
        public string SUBJ_LVL { get; set; }
        public Nullable<bool> SUBJ_STATE { get; set; }
        public Nullable<decimal> TEACHER_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLASSES_TBL> CLASSES_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBJECT_PER_CLASS_TBL> SUBJECT_PER_CLASS_TBL { get; set; }
    }
}
