//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIFORM_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNIFORM_TBL()
        {
            this.ORDER_TBL = new HashSet<ORDER_TBL>();
        }
    
        public decimal UNIFORM_ID { get; set; }
        public Nullable<decimal> UNIFORM_CODE { get; set; }
        public string UNIFORM_TYPE { get; set; }
        public string UNIFORM_SIZE { get; set; }
        public Nullable<decimal> UNIFORM_PRICE { get; set; }
        public Nullable<bool> UNIFORM_STATE { get; set; }
        public string NOTES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_TBL> ORDER_TBL { get; set; }
    }
}
