//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_TBL
    {
        public decimal USER_ID { get; set; }
        public Nullable<decimal> USER_CODE { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_TYPE { get; set; }
        public Nullable<decimal> EMP_ID { get; set; }
    
        public virtual EMPLOYEE_TBL EMPLOYEE_TBL { get; set; }
    }
}
