//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_NURSERT_DATABASE_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISIT_TBL
    {
        public decimal VST_ID { get; set; }
        public Nullable<decimal> VST_CODE { get; set; }
        public string VSTR_NAME { get; set; }
        public string VSTR_SSID { get; set; }
        public string VSTR_MOB { get; set; }
        public string VST_PRPS { get; set; }
        public Nullable<System.DateTime> VST_DATE { get; set; }
        public Nullable<System.TimeSpan> VST_TIME { get; set; }
        public Nullable<decimal> CLD_ID { get; set; }
    
        public virtual CHILD_TBL CHILD_TBL { get; set; }
    }
}
